# Generated by Django 5.2.7 on 2025-10-30 02:48

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orig_url', models.URLField(max_length=2000, verbose_name='Original URL')),
                ('short_code', models.CharField(default=api.models.generate_code, max_length=8, unique=True, verbose_name='Short Code')),
                ('clicks', models.IntegerField(default=0, verbose_name='Click Count')),
                ('last_clicked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Short Link',
                'verbose_name_plural': 'Short Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
